#
# Copyright (C) 2025 aosPB-Project
#

# Boot animation
TARGET_BOOT_ANIMATION_RES := 1080
TARGET_SCREEN_HEIGHT := 2400
TARGET_SCREEN_WIDTH := 1080

# aosPB - Stuff
CUSTOM_BUILDTYPE := OFFICIAL
IS_SIGNED := true
CUSTOM_MAINTAINER := PaperBoy

# OMX Service
TARGET_SUPPORTS_OMX_SERVICE := false